name: pos_map_app
description: 'Sample Map App'

version: 1.0.0+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  freezed_annotation: ^3.1.0
  freezed: ^3.2.0
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/map_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: IRANSans
      fonts:
        - asset: assets/fonts/IRANSansX-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/IRANSansX-Light.ttf
          weight: 300
        - asset: assets/fonts/IRANSansX-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/IRANSansX-Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSansX-Bold.ttf
          weight: 700
        - asset: assets/fonts/IRANSansX-Black.ttf
          weight: 900
